# Generated by Django 3.2.9 on 2022-11-04 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20221104_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='photos/products/1.jpg', upload_to='photos/products'),
            preserve_default=False,
        ),
    ]
