# Generated by Django 3.2.9 on 2022-11-04 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_gallery_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='images',
            new_name='image',
        ),
    ]
