# Generated by Django 3.2.9 on 2023-02-16 20:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('category', '0002_auto_20230217_0023'),
        ('store', '0006_rename_images_gallery_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'گالری', 'verbose_name_plural': 'گالری'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'کالا', 'verbose_name_plural': 'کالا ها'},
        ),
        migrations.AlterModelOptions(
            name='variation',
            options={'verbose_name': 'مشخصه', 'verbose_name_plural': 'مشخصات'},
        ),
        migrations.RemoveField(
            model_name='variation',
            name='image',
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(upload_to='photos/products', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='کالای مرتبط'),
        ),
        migrations.AlterField(
            model_name='product',
            name='available',
            field=models.BooleanField(default=True, verbose_name='در دسترس؟'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category', verbose_name='دسته بندی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, max_length=1024, verbose_name='مشخصات'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.IntegerField(default=0, verbose_name='تخفیف'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='آیدی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='photos/products', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='product',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ تغییر'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='نام به احنبی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(verbose_name='شیتیل'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='اسلاگ'),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(blank=True, max_length=500, verbose_name='سخنوری'),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ درافشانی'),
        ),
        migrations.AlterField(
            model_name='review',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='کالای مرتبط'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.FloatField(verbose_name='امتیازدهی'),
        ),
        migrations.AlterField(
            model_name='review',
            name='status',
            field=models.BooleanField(default=True, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='review',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='به روز رسانی نظز'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='variation',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='variation',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='در دسترس؟'),
        ),
        migrations.AlterField(
            model_name='variation',
            name='parameter',
            field=models.CharField(choices=[('color', 'رنگ'), ('size', 'سایز')], max_length=10, verbose_name='لیبل'),
        ),
        migrations.AlterField(
            model_name='variation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='کالای مرتبط'),
        ),
        migrations.AlterField(
            model_name='variation',
            name='stock',
            field=models.IntegerField(default=1, verbose_name='موجودی'),
        ),
        migrations.AlterField(
            model_name='variation',
            name='value',
            field=models.CharField(max_length=20, verbose_name='ویزگی'),
        ),
    ]
