# Generated by Django 3.2.12 on 2022-09-30 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=20)),
                ('notes', models.CharField(blank=True, max_length=256, verbose_name='Order Notes')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('new', 'جدید'), ('pending', 'در دست بررسی'), ('certified', 'سفارش معتبر'), ('sent', ' ارسال شده'), ('delivered', 'تحویل شده'), ('separator', '--------------------'), ('uncertified', 'سفارش نامعتبر'), ('not_sent', 'عدم ارسال'), ('undelivered', 'عدم تحویل'), ('canceled', 'داستان'), ('failed', 'قطعی آب')], default='new', max_length=20)),
                ('cost', models.IntegerField(default=0)),
                ('discounts', models.IntegerField(default=0)),
                ('shipping_cost', models.IntegerField(default=0)),
                ('must_be_paid', models.IntegerField(default=0)),
                ('buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_id', models.CharField(max_length=30)),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos/transactions')),
                ('amount', models.IntegerField(verbose_name='Transaction Amount')),
                ('order_key', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('validation', models.CharField(choices=[('pending', 'در دست بررسی'), ('valid', 'معتبر'), ('invalid', 'نامعتبر')], default='pending', max_length=20)),
                ('method', models.CharField(choices=[('reserve', 'رزرو'), ('zarinpal', 'زرین پال'), ('bank_portal', 'درگاه پرداخت بانکی')], max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('performer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='purchase.receipt')),
            ],
        ),
        migrations.CreateModel(
            name='OrderReceiver',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fname', models.CharField(blank=True, max_length=30, verbose_name="Receiver's First Name")),
                ('lname', models.CharField(blank=True, max_length=30, verbose_name="Receiver's Last Name")),
                ('phone', models.CharField(blank=True, max_length=11, verbose_name="Receiver's Phone Number")),
                ('postal_code', models.CharField(max_length=10, verbose_name='Postal Code')),
                ('province', models.CharField(max_length=30, verbose_name='Province')),
                ('city', models.CharField(max_length=30, verbose_name='City')),
                ('address', models.CharField(max_length=256, verbose_name='Address')),
                ('related_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderedProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=0)),
                ('color', models.CharField(max_length=20)),
                ('size', models.CharField(max_length=20)),
                ('cost', models.IntegerField()),
                ('delivered', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('anything_wrong', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
                ('variations', models.ManyToManyField(blank=True, to='store.Variation')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='purchase.orderreceiver'),
        ),
        migrations.AddField(
            model_name='order',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchase.transaction'),
        ),
    ]
