# Generated by Django 3.2.9 on 2023-08-28 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=20, verbose_name='شماره سفارش')),
                ('notes', models.CharField(blank=True, max_length=256, verbose_name='لحاظیات')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='تاریخ به روزرسانی')),
                ('status', models.CharField(choices=[('new', 'جدید'), ('pending', 'در دست بررسی'), ('verified', 'سفارش معتبر'), ('indebt', 'شامل بدهی'), ('sent', ' ارسال شده'), ('delivered', 'تحویل شده'), ('separator', '--------------------'), ('invalid', 'سفارش نامعتبر'), ('not_sent', 'عدم ارسال'), ('undelivered', 'عدم تحویل'), ('canceled', 'داستان'), ('failed', 'قطعی آب')], default='new', max_length=20, verbose_name='وضعیت')),
                ('cost', models.IntegerField(default=0, verbose_name='هزینه')),
                ('discounts', models.IntegerField(default=0, verbose_name='تخفیفی جات')),
                ('shipping_cost', models.IntegerField(default=0, verbose_name='هزینه ارسال')),
                ('must_be_paid', models.IntegerField(default=0, verbose_name='هزینه نهایی')),
                ('seen', models.BooleanField(default=False, verbose_name='مشاهده توسط ادمین')),
                ('whats_wrong', models.TextField(blank=True, max_length=256, null=True, verbose_name='علت رد سفارش')),
                ('buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='مالک زدوبند')),
            ],
            options={
                'verbose_name': 'زدوبند',
                'verbose_name_plural': 'زدوبندها',
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='آیدی')),
                ('reference_id', models.CharField(max_length=30, verbose_name='کد رهیگیری')),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos/transactions', verbose_name='تصویر')),
                ('amount', models.IntegerField(verbose_name='مقدار تراکنش')),
                ('order_key', models.CharField(max_length=20, verbose_name='شماره سفارش')),
            ],
            options={
                'verbose_name': 'رسید',
                'verbose_name_plural': 'رسیدها',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='آیدی')),
                ('validation', models.CharField(choices=[('pending', 'در دست بررسی'), ('valid', 'معتبر'), ('invalid', 'نامعتبر')], default='pending', max_length=20, verbose_name='صحت تراکنش')),
                ('method', models.CharField(choices=[('reserve', 'رزرو'), ('zarinpal', 'زرین پال'), ('bank_portal', 'درگاه پرداخت بانکی')], max_length=20, verbose_name='روش پرداخت')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('performer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='زدوبند کننده')),
                ('receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='purchase.receipt', verbose_name='رسید')),
            ],
            options={
                'verbose_name': 'تراکنش',
                'verbose_name_plural': 'تراکنش ها',
            },
        ),
        migrations.CreateModel(
            name='PurchasedItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='آیدی')),
                ('quantity', models.IntegerField(default=0, verbose_name='تعداد')),
                ('cost', models.IntegerField(verbose_name='هزینه')),
                ('delivered', models.BooleanField(default=False, verbose_name='تحویل شده')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('date_updated', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ به روزرسانی')),
                ('anything_wrong', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='مشکل پشکل؟')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='مالک زدوبند')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.order', verbose_name='سفارش مربوطه')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='کالا')),
                ('variation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.variation', verbose_name='گونه')),
            ],
            options={
                'verbose_name': 'کالای زدوبندی',
                'verbose_name_plural': 'کالاهای زدوبندی',
            },
        ),
        migrations.CreateModel(
            name='OrderReceiver',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='آیدی')),
                ('fname', models.CharField(blank=True, max_length=30, verbose_name='اسم')),
                ('lname', models.CharField(blank=True, max_length=30, verbose_name='فامیلی')),
                ('phone', models.CharField(blank=True, max_length=11, verbose_name='تیلیف')),
                ('postal_code', models.CharField(max_length=10, verbose_name='کد پستی')),
                ('province', models.CharField(max_length=30, verbose_name='استان')),
                ('city', models.CharField(max_length=30, verbose_name='شهرستان')),
                ('address', models.TextField(max_length=256, verbose_name='نشونی')),
                ('related_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر مربوطه')),
            ],
            options={
                'verbose_name': 'گیرنده سفارش',
                'verbose_name_plural': 'گیرنده های سفارش',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='purchase.orderreceiver', verbose_name='گیرنده'),
        ),
        migrations.AddField(
            model_name='order',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchase.transaction', verbose_name='تراکنش'),
        ),
    ]
