# Generated by Django 3.2.9 on 2023-05-06 21:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0001_initial'),
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderreceiver',
            options={'verbose_name': 'گیرنده سفارش', 'verbose_name_plural': 'گیرنده های سفارش'},
        ),
        migrations.RemoveField(
            model_name='purchaseditem',
            name='color',
        ),
        migrations.RemoveField(
            model_name='purchaseditem',
            name='size',
        ),
        migrations.AlterField(
            model_name='order',
            name='buyer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='مالک زدوبند'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cost',
            field=models.IntegerField(default=0, verbose_name='هزینه'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ به روزرسانی'),
        ),
        migrations.AlterField(
            model_name='order',
            name='discounts',
            field=models.IntegerField(default=0, verbose_name='تخفیفی جات'),
        ),
        migrations.AlterField(
            model_name='order',
            name='key',
            field=models.CharField(max_length=20, verbose_name='شماره سفارش'),
        ),
        migrations.AlterField(
            model_name='order',
            name='must_be_paid',
            field=models.IntegerField(default=0, verbose_name='هزینه نهایی'),
        ),
        migrations.AlterField(
            model_name='order',
            name='notes',
            field=models.CharField(blank=True, max_length=256, verbose_name='لحاظیات'),
        ),
        migrations.AlterField(
            model_name='order',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='purchase.orderreceiver', verbose_name='گیرنده'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_cost',
            field=models.IntegerField(default=0, verbose_name='هزینه ارسال'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'جدید'), ('pending', 'در دست بررسی'), ('certified', 'سفارش معتبر'), ('sent', ' ارسال شده'), ('delivered', 'تحویل شده'), ('separator', '--------------------'), ('uncertified', 'سفارش نامعتبر'), ('not_sent', 'عدم ارسال'), ('undelivered', 'عدم تحویل'), ('canceled', 'داستان'), ('failed', 'قطعی آب')], default='new', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='order',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchase.transaction', verbose_name='تراکنش'),
        ),
        migrations.AlterField(
            model_name='orderreceiver',
            name='address',
            field=models.TextField(max_length=256, verbose_name='نشونی'),
        ),
        migrations.AlterField(
            model_name='orderreceiver',
            name='city',
            field=models.CharField(max_length=30, verbose_name='شهرستان'),
        ),
        migrations.AlterField(
            model_name='orderreceiver',
            name='fname',
            field=models.CharField(blank=True, max_length=30, verbose_name='اسم'),
        ),
        migrations.AlterField(
            model_name='orderreceiver',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='آیدی'),
        ),
        migrations.AlterField(
            model_name='orderreceiver',
            name='lname',
            field=models.CharField(blank=True, max_length=30, verbose_name='فامیلی'),
        ),
        migrations.AlterField(
            model_name='orderreceiver',
            name='phone',
            field=models.CharField(blank=True, max_length=11, verbose_name='تیلیف'),
        ),
        migrations.AlterField(
            model_name='orderreceiver',
            name='postal_code',
            field=models.CharField(max_length=10, verbose_name='کد پستی'),
        ),
        migrations.AlterField(
            model_name='orderreceiver',
            name='province',
            field=models.CharField(max_length=30, verbose_name='استان'),
        ),
        migrations.AlterField(
            model_name='orderreceiver',
            name='related_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر مربوطه'),
        ),
        migrations.AlterField(
            model_name='purchaseditem',
            name='anything_wrong',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='مشکل پشکل؟'),
        ),
        migrations.AlterField(
            model_name='purchaseditem',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='مالک زدوبند'),
        ),
        migrations.AlterField(
            model_name='purchaseditem',
            name='cost',
            field=models.IntegerField(verbose_name='هزینه'),
        ),
        migrations.AlterField(
            model_name='purchaseditem',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='purchaseditem',
            name='date_updated',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ به روزرسانی'),
        ),
        migrations.AlterField(
            model_name='purchaseditem',
            name='delivered',
            field=models.BooleanField(default=False, verbose_name='تحویل شده'),
        ),
        migrations.AlterField(
            model_name='purchaseditem',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='آیدی'),
        ),
        migrations.AlterField(
            model_name='purchaseditem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.order', verbose_name='سفارش مربوطه'),
        ),
        migrations.AlterField(
            model_name='purchaseditem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='کالا'),
        ),
        migrations.AlterField(
            model_name='purchaseditem',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='تعداد'),
        ),
        migrations.AlterField(
            model_name='purchaseditem',
            name='variation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.variation', verbose_name='گونه'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='amount',
            field=models.IntegerField(verbose_name='مقدار تراکنش'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='آیدی'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/transactions', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='order_key',
            field=models.CharField(max_length=20, verbose_name='شماره سفارش'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='reference_id',
            field=models.CharField(max_length=30, verbose_name='کد رهیگیری'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='آیدی'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='method',
            field=models.CharField(choices=[('reserve', 'رزرو'), ('zarinpal', 'زرین پال'), ('bank_portal', 'درگاه پرداخت بانکی')], max_length=20, verbose_name='روش پرداخت'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='performer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='زدوبند کننده'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='purchase.receipt', verbose_name='رسید'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='validation',
            field=models.CharField(choices=[('pending', 'در دست بررسی'), ('valid', 'معتبر'), ('invalid', 'نامعتبر')], default='pending', max_length=20, verbose_name='صحت تراکنش'),
        ),
    ]
