# Generated by Django 3.2.9 on 2023-05-06 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_auto_20230507_0105'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseditem',
            options={'verbose_name': 'کالای زدوبندی', 'verbose_name_plural': 'کالاهای زدوبندی'},
        ),
    ]
