# Generated by Django 3.2.12 on 2022-10-31 01:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('purchase', '0002_alter_orderreceiver_address'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderedProduct',
            new_name='PurchasedItem',
        ),
    ]
