# Generated by Django 3.2.9 on 2023-05-07 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0003_alter_purchaseditem_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='seen',
            field=models.BooleanField(default=False, verbose_name='مشاهده توسط ادمین'),
        ),
    ]
