# Generated by Django 3.2.9 on 2023-05-13 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0008_alter_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='whats_wrong',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'جدید'), ('pending', 'در دست بررسی'), ('verified', 'سفارش معتبر'), ('sent', ' ارسال شده'), ('delivered', 'تحویل شده'), ('separator', '--------------------'), ('invalid', 'سفارش نامعتبر'), ('not_sent', 'عدم ارسال'), ('undelivered', 'عدم تحویل'), ('canceled', 'داستان'), ('failed', 'قطعی آب')], default='new', max_length=20, verbose_name='وضعیت'),
        ),
    ]
