# Generated by Django 3.2.9 on 2023-05-21 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0011_alter_order_whats_wrong'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'جدید'), ('pending', 'در دست بررسی'), ('verified', 'سفارش معتبر'), ('indebt', 'شامل بدهی'), ('sent', ' ارسال شده'), ('delivered', 'تحویل شده'), ('separator', '--------------------'), ('invalid', 'سفارش نامعتبر'), ('not_sent', 'عدم ارسال'), ('undelivered', 'عدم تحویل'), ('canceled', 'داستان'), ('failed', 'قطعی آب')], default='new', max_length=20, verbose_name='وضعیت'),
        ),
    ]
