# Generated by Django 3.2.12 on 2022-10-25 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('name_fa', models.CharField(max_length=30, unique=True, verbose_name='نام')),
                ('slug', models.SlugField(max_length=30, unique=True)),
                ('description', models.TextField(blank=True, max_length=256)),
                ('icon', models.ImageField(blank=True, upload_to='photos/categories/')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
    ]
