# Generated by Django 3.2.9 on 2023-08-28 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='آیدی')),
                ('name', models.CharField(max_length=64, verbose_name='نام (انگلیسی)')),
                ('name_fa', models.CharField(max_length=64, verbose_name='نام (فارسی)')),
                ('description', models.CharField(blank=True, max_length=1024, verbose_name='توضیحات')),
                ('location', models.CharField(max_length=128, verbose_name='آدرس')),
                ('slug', models.SlugField(max_length=64, unique=True, verbose_name='اسلاگ')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='مالک')),
            ],
            options={
                'verbose_name': 'فروشگاه',
                'verbose_name_plural': 'فروشگاه ها',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/shops', verbose_name='تصویر')),
                ('shop', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='shop.shop', verbose_name='فروشگاه')),
            ],
            options={
                'verbose_name': 'گالری',
                'verbose_name_plural': 'گالری',
            },
        ),
    ]
