# Generated by Django 3.2.9 on 2023-06-02 07:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0002_alter_shop_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shop',
            options={'verbose_name': 'فروشگاه', 'verbose_name_plural': 'فروشگاه ها'},
        ),
        migrations.AlterField(
            model_name='gallery',
            name='shop',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='shop.shop', verbose_name='فروشگاه'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='description',
            field=models.CharField(blank=True, max_length=1024, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='آیدی'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='location',
            field=models.CharField(max_length=128, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(max_length=64, verbose_name='نام (انگلیسی)'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='name_fa',
            field=models.CharField(max_length=64, verbose_name='نام (فارسی)'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='مالک'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='slug',
            field=models.SlugField(max_length=64, unique=True, verbose_name='اسلاگ'),
        ),
    ]
