# Generated by Django 3.2.12 on 2022-09-30 19:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(blank=True, max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('cost', models.IntegerField(default=0)),
                ('discounts', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TakenProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=0)),
                ('is_available', models.BooleanField(default=True)),
                ('exact_stock', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
