# Generated by Django 3.2.9 on 2023-02-16 20:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0007_auto_20230217_0023'),
        ('stack', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stack',
            name='belongs_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='به نام'),
        ),
        migrations.AlterField(
            model_name='stack',
            name='cost',
            field=models.IntegerField(default=0, verbose_name='شیتیل موردنیاز'),
        ),
        migrations.AlterField(
            model_name='stack',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده'),
        ),
        migrations.AlterField(
            model_name='stack',
            name='discounts',
            field=models.IntegerField(default=0, verbose_name='تخفیف'),
        ),
        migrations.AlterField(
            model_name='stack',
            name='sid',
            field=models.CharField(blank=True, max_length=50, verbose_name='شناسه خرمن'),
        ),
        migrations.AlterField(
            model_name='takenproduct',
            name='exact_stock',
            field=models.IntegerField(blank=True, null=True, verbose_name='موجودی دقیق'),
        ),
        migrations.AlterField(
            model_name='takenproduct',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='در دسترس؟'),
        ),
        migrations.AlterField(
            model_name='takenproduct',
            name='preferred_variations',
            field=models.ManyToManyField(blank=True, to='store.Variation', verbose_name='مشخصهات ترجیحی'),
        ),
        migrations.AlterField(
            model_name='takenproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='کالا'),
        ),
        migrations.AlterField(
            model_name='takenproduct',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='شمار'),
        ),
        migrations.AlterField(
            model_name='takenproduct',
            name='stack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stack.stack', verbose_name='خرمن'),
        ),
    ]
