# Generated by Django 3.2.12 on 2022-09-30 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stack', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='takenproduct',
            name='preferred_variations',
            field=models.ManyToManyField(blank=True, to='store.Variation'),
        ),
        migrations.AddField(
            model_name='takenproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product'),
        ),
        migrations.AddField(
            model_name='takenproduct',
            name='stack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stack.stack'),
        ),
        migrations.AddField(
            model_name='stack',
            name='belongs_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
