# Generated by Django 3.2.9 on 2023-06-02 21:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=30, verbose_name='اسم')),
                ('lname', models.CharField(max_length=30, verbose_name='فامیل')),
                ('phone', models.CharField(max_length=11, unique=True, verbose_name='تیلیف')),
                ('email', models.CharField(max_length=100, unique=True, verbose_name='نومه')),
                ('ip', models.CharField(blank=True, max_length=20, verbose_name='IP')),
                ('joining_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ فیلی شدن')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='آخرین دخول')),
                ('is_staff', models.BooleanField(default=False, verbose_name='فیل درباری')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='فیل شاه')),
                ('is_activated', models.BooleanField(default=False, verbose_name='فعال شدن اکانت')),
            ],
            options={
                'verbose_name': 'فیلی',
                'verbose_name_plural': 'فیلی ها',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='کدپستی')),
                ('province', models.CharField(blank=True, max_length=30, verbose_name='استان')),
                ('city', models.CharField(blank=True, max_length=30, verbose_name='شهرستان')),
                ('address', models.TextField(blank=True, max_length=256, verbose_name='نشونی')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='photos/avatars/')),
                ('last_email_date', models.DateTimeField(auto_now_add=True)),
                ('debt', models.IntegerField(default=0, verbose_name='بدهی شما')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پروفایل',
                'verbose_name_plural': 'پروفایل ها',
            },
        ),
    ]
