# Generated by Django 3.2.9 on 2023-05-07 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='activated',
            new_name='is_activated',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='joined',
            new_name='joining_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='سوپرفیل'),
        ),
    ]
