# Generated by Django 3.2.9 on 2023-06-02 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_email_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
