# Generated by Django 3.2.9 on 2023-05-07 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20230508_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='فیل شاه'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_activated',
            field=models.BooleanField(default=False, verbose_name='فعال شدن اکانت'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='فیل شاه'),
        ),
    ]
