# Generated by Django 3.2.9 on 2023-05-21 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20230508_0155'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='debt',
            field=models.IntegerField(default=0, verbose_name='بدهی شما'),
        ),
    ]
