# Generated by Django 3.2.9 on 2023-06-02 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_profile_debt'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_email_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
